spring:
  config:
    import: optional:configserver:${CONFIGURATION-SERVER:http://localhost:8081}
  application:
    name: chat-service

kafka-setup:
  url: ${KAFKA_URL:localhost:9092}

services:
  auth:
    url: ${AUTH_URL:http://localhost:8082/api/v1/auth/}