"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authController_1 = require("../controllers/authController");
const auth_1 = require("../middleware/auth");
const storage_1 = require("../utils/storage");
const router = (0, express_1.Router)();
router.post('/register', authController_1.register);
router.get('/verify-email', authController_1.verifyEmail);
router.post('/login', authController_1.loginCheck);
router.post('/logout', auth_1.authenticate, authController_1.logout);
router.get('/verify-login', authController_1.verifyLoginDevice);
router.post('/forgot-password', authController_1.requestPasswordReset);
router.post('/reset-password', authController_1.resetPassword);
router.post('/delete-account', auth_1.authenticate, authController_1.requestAccountDeletion);
router.post('/recover-account', authController_1.recoverAccount);
router.put('/profile', auth_1.authenticate, storage_1.avatarUpload, authController_1.editProfile);
router.get('/privacy-settings', auth_1.authenticate, authController_1.getPrivacySettings);
router.put('/privacy-settings', auth_1.authenticate, authController_1.updatePrivacySettings);
exports.default = router;
